# -*- coding: utf-8 -*-
"""Exploratory-Data-Analysis-EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFmIoj0QYqhlE_j5gkcjPPBpRPEk5wha
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Titanic-Dataset.csv")  # Replace with your path if needed

print("\n=== Summary Statistics ===")
print(df.describe(include='all'))

numeric_cols = df.select_dtypes(include='number').columns

for col in numeric_cols:
    plt.figure(figsize=(6, 4))
    sns.histplot(df[col].dropna(), kde=True)
    plt.title(f"Histogram of {col}")
    plt.tight_layout()
    plt.savefig(f"hist_{col}.png")
    plt.close()

for col in numeric_cols:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot of {col}")
    plt.tight_layout()
    plt.savefig(f"box_{col}.png")
    plt.close()

plt.figure(figsize=(10, 8))
corr = df[numeric_cols].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Matrix")
plt.tight_layout()
plt.savefig("correlation_matrix.png")
plt.close()

subset_cols = ['Age', 'Fare', 'Pclass', 'Survived']
df_subset = df[subset_cols].dropna()
sns.pairplot(df_subset, hue="Survived", diag_kind="hist")
plt.savefig("pairplot.png")
plt.close()